### ISSUE TITLE
Nextcloud group folder checkbox

### ISSUE THREAD

**Issue by shahnenigans** [Jean28518/libre-workspace#101]
When the checkbox "Nextcloud-Gruppenordner" is checked there is an error message after creating the group:
"There are no commands defined in the "groupfolder" namespace.
![image](https://github.com/Jean28518/libre-workspace/assets/88903532/4b068ff6-7b18-4a5b-b001-39ce07e8765d)
Then no group folder is created.

**Comment by Jean28518** [comment]
Thank you very much for your report!
Can you pls specify which was your groupname?
I can't confirm this bug.

**Comment by shahnenigans** [comment]
Bug cannot be reproduced in 0.5.5 because of different error.
`Error: Nextcloud is not available. Please install Nextcloud first.`  

Upgrade to 0.6.0
`Error: Nextcloud is not available. Please install Nextcloud first.`  

Neither reboot nor clicking "install nextcloud" did solve this issue.
I will install a fresh 0.6.0 instance in my lab and check that later.

**Comment by shahnenigans** [comment]
I cannot reproduce it in 0.6.0.
