### ISSUE TITLE
Installation via *.deb preinstalled Debian “freezes” at 99%.

### ISSUE THREAD

**Issue by syrabo** [Jean28518/libre-workspace#115]
The installation with a preinstalled Debian freezes, probably at the end of the whole installation; 
A progress bar runs through to 99%.

In another screen in top there is no running process except for “apt”; apt does not consume any resources; CPU and RAM are not loaded, so I do not suspect any compilation.

I have not repeated this process and cannot verify whether it is just a “flash in the pan”; I then did it via the *.iso; here the system fails at nextcloud  [https://github.com/Jean28518/libre-workspace/issues/114](https://github.com/Jean28518/libre-workspace/issues/114)

**Comment by Jean28518** [comment]
Is already something running at port 80 on your server?
At least in one environment I tested this was the issue.
I updated the corresponding caddy call

**Comment by syrabo** [comment]
I installed it on two different servers yesterday. Both installations went through; the only thing that remained was a line that _apt has no rights (or something like that); I was able to access the installed instance in the browser. 

Many thanks for the answer. This message has been resolved for me.

**Comment by Jean28518** [comment]
The warning in the end is normal for now.
Great :)
