### ISSUE TITLE
GUI Error while Installing

### ISSUE THREAD

**Issue by gelbphoenix** [Jean28518/libre-workspace#130]
Hey @Jean28518,

i have found this bug. The link to the portal is vanished as seen by the completed #113 while the last sentence remains. 
![image](https://github.com/Jean28518/libre-workspace/assets/122753910/fad5165b-a2fe-4cfb-af36-2cdd8c28a648)

**Comment by Jean28518** [comment]
Thanks for your notice, I fixed it :)
