### ISSUE TITLE
New Patch: dns forwarder resolve only

### ISSUE THREAD

**Issue by Jean28518** [Jean28518/libre-workspace#134]
in /etc/samba/smb.conf

Add: 
dns forwarder resolve only

(https://www.bsi.bund.de/DE/Themen/Unternehmen-und-Organisationen/Cyber-Sicherheitslage/Reaktion/CERT-Bund/CERT-Bund-Reports/HowTo/Offene-DNS-Resolver/Offene-DNS-Resolver.html)

**Comment by gelbphoenix** [comment]
Maybe the solution is the `hosts allow` option in `/etc/samba/smb.conf`

**Comment by gelbphoenix** [comment]
I don't know if this Issue is ready to close as finished.

Since updating to v0.7.X the result of the dig command is:

```
; <<>> DiG 9.18.28 <<>> cert-bund.de @116.203.88.99
;; global options: +cmd
;; no servers could be reached
```

**Comment by Jean28518** [comment]
Reverted this. It will be applied via the patch :)
