### ISSUE TITLE
[FEATURE] Pretty URL for Nextcloud

### ISSUE THREAD

**Issue by gelbphoenix** [Jean28518/libre-workspace#136]
Could we standardly replace "cloud.{DOMAIN}/index.php" with "cloud{DOMAIN}/"?

Example:
`cloud.{DOMAIN}/index.php/apps/files/files` would turn into `cloud.{DOMAIN}/apps/files/files`

It would only require two changes to the already existing setup of Nextcloud.

1. Adding "htaccess.RewriteBase" to the Nextcloud config via command in setup_nextcloud.sh:
```bash
sudo -u www-data php /var/www/nextcloud/occ config:system:set htaccess.RewriteBase --value="/"
```
Then updating .htaccess (if needed):
```bash
sudo -u www-data php /var/www/nextcloud/occ maintenance:update:htaccess
```

2. Adding a value to the php-fpm.sock in the Caddyfile entry for cloud.{DOMAIN}:
```
  php_fastcgi unix//var/run/php/php-fpm.sock {
    env front_controller_active true
  }
```

**Comment by Jean28518** [comment]
Thank you very much for your feature request :)
I personally am not a fan of those cosmetic changes but I will test it and if everything is right, new instances will get this feature :)

**Comment by gelbphoenix** [comment]
Also I noted today that the same redir for `/index.php/settings/users` must be implemented for `/settings/users`
