### ISSUE TITLE
[BUG]: Add robots.txt

### ISSUE THREAD

**Issue by gelbphoenix** [Jean28518/libre-workspace#165]
We should add a robots.txt file to indicate that webcrawlers shouldn't index the Libre Workspace Portal.

**Comment by gelbphoenix** [comment]
Classified this issue as a bug. 

> [!NOTE] 
> This isn't a bug in the sense that a person wrote buggy code but in the sense that it isn't intended that the Libre Workspace Portal shall be indexed by webcrawlers like googlebot.

**Comment by Jean28518** [comment]
Thanks!
