### ISSUE TITLE
Disabling the Administrator account breaks the login page

### ISSUE THREAD

**Issue by ikem-krueger** [Jean28518/libre-workspace#174]
I created a user and gave him admin permissions. After that I disabled the "Administrator" account.

I tried to login with the new account in Nextcloud, which caused an error.

I tried to login with the new account in "Verwaltung" and that didn't work.

At that state, I can't login with the new account or the "Administrator" account.

**Comment by Jean28518** [comment]
This is because the apps and the libre workspace portal itself are identifying theirselfs as Administrator.
I will add an option which prevents disabling the administrator user. Thanks for reporting!
