### ISSUE TITLE
[BUG]: Update log can't be opened when a backup failed

### ISSUE THREAD

**Issue by gelbphoenix** [Jean28518/libre-workspace#175]
### System infos:
- Libre Workspace version: v0.7.1
- Server OS: Debian 12 (Bookworm)
- Modules:
  - Nextcloud (Version: 30.0.0)
  - Matrix
  - Collabora (Version: 24.04.7.2)
- Additional installed services:
  - Mailcow (Version: 2024-08a)

### What happend prior to noticing the error?
Libre Workspace did an update and backup as planned. The backup finished with an error. I wanted to look at the update log in the portal to check if I should restart the server.

### What should happen?
The update log of a day should be visible.

### What happend?
The error log of the borg backup was only visible and it prevented the visibility of the update log.

**Comment by Jean28518** [comment]
Thank you very much for your good description :)
