### ISSUE TITLE
[BUG]: Deprecated version of actions/upload-artifact

### ISSUE THREAD

**Issue by gelbphoenix** [Jean28518/libre-workspace#178]
[This run](https://github.com/Jean28518/libre-workspace/actions/runs/11216232490/job/31175078903) failed because actions/upload-artifact is in the deprecated version v1.

https://github.com/Jean28518/libre-workspace/blob/8909edc7e12d329acd8c9ece397f4dbdf0b2d8d3/.github/workflows/build.yml#L21

**Comment by Jean28518** [comment]
Fixed, thanks for pointing out :)
