### ISSUE TITLE
New installation option: "Libre Workspace lite"

### ISSUE THREAD

**Issue by Jean28518** [Jean28518/libre-workspace#183]
Just use Libre Workspace for administration of a linux server just like cockpit and with addon-Support.

Should we install samba support?
Maybe we should set also samba as a module which can be installed afterwards. (and only removed with warning that this should only be done if no further module uses the samba module. (NORMALLY YOU DON'T WANT TO DO THIS)
(We should also care that libre workspace portal gives itself an local administrator if uninstalling this module)

**Comment by gelbphoenix** [comment]
Wouldn't this need a major rewrite for Libre-Workspace?

**Comment by Jean28518** [comment]
We don't need a major rewrite.
I am already using some servers with ony "Libre Workspace Lite" experience.
The only thing is to make an official installation method and to modularize the samba support.
